//! Integration test: chi-separation on forward-simulated head phantom data
//!
//! Uses data generated by qsm-forward with tissue-informed chi+/chi- maps.
//! Path: ../qsm-forward/output/

mod common;

use std::path::Path;
use std::time::Instant;
use common::{load_nifti_file, correlation, rmse};
use qsm_core::separation::chi_sep_medi;
use qsm_core::kernels::dipole::dipole_kernel;
use qsm_core::fft::{fft3d_real, ifft3d_real};

/// Compute local field (Hz) from chi map (ppm) via dipole convolution.
fn compute_local_field_hz(
    chi: &[f64], mask: &[u8],
    nx: usize, ny: usize, nz: usize,
    vsx: f64, vsy: f64, vsz: f64,
    bdir: (f64, f64, f64),
    cf: f64,
) -> Vec<f64> {
    let n = nx * ny * nz;

    // Dipole kernel (real, in k-space)
    let d_kernel = dipole_kernel(nx, ny, nz, vsx, vsy, vsz, bdir);

    // Forward FFT of chi
    let mut chi_k = fft3d_real(chi, nx, ny, nz);

    // Multiply by dipole kernel in k-space
    for i in 0..n {
        chi_k[i] *= d_kernel[i];
    }

    // Inverse FFT → field in ppm
    let field_ppm = ifft3d_real(&chi_k, nx, ny, nz);

    // Convert ppm → Hz and subtract mean within mask
    let ppm_to_hz = cf * 1e-6; // field_Hz = field_ppm * gamma * B0 = field_ppm * cf * 1e-6
    let mut field_hz: Vec<f64> = field_ppm.iter().map(|&v| v * ppm_to_hz).collect();

    let mut sum = 0.0;
    let mut count = 0usize;
    for i in 0..n {
        if mask[i] > 0 {
            sum += field_hz[i];
            count += 1;
        }
    }
    if count > 0 {
        let mean = sum / count as f64;
        for i in 0..n {
            if mask[i] > 0 {
                field_hz[i] -= mean;
            } else {
                field_hz[i] = 0.0;
            }
        }
    }

    field_hz
}

#[test]
#[ignore] // Run with: cargo test --test chisep_integration -- --ignored --nocapture
fn test_chisep_on_forward_phantom() {
    let base = "../../qsm-forward/output";
    let deriv = &format!("{}/derivatives/qsm-forward/sub-1/anat", base);

    // Check data exists
    if !Path::new(deriv).exists() {
        println!("Skipping: forward phantom data not found at {}", deriv);
        return;
    }

    // Load data
    println!("[INFO] Loading forward phantom data...");
    let chi_nii = load_nifti_file(&format!("{}/sub-1_Chimap.nii", deriv))
        .expect("Failed to load Chimap");
    let chi_pos_gt = load_nifti_file(&format!("{}/sub-1_Chimap-pos.nii", deriv))
        .expect("Failed to load Chimap-pos");
    let chi_neg_gt = load_nifti_file(&format!("{}/sub-1_Chimap-neg.nii", deriv))
        .expect("Failed to load Chimap-neg");
    let r2prime_nii = load_nifti_file(&format!("{}/sub-1_R2prime.nii", deriv))
        .expect("Failed to load R2prime");
    let mask_nii = load_nifti_file(&format!("{}/sub-1_mask.nii", deriv))
        .expect("Failed to load mask");

    // First echo magnitude for edge weighting
    let mag_nii = load_nifti_file(&format!("{}/sub-1/anat/sub-1_echo-1_part-mag_MEGRE.nii", base))
        .expect("Failed to load magnitude");

    let (nx, ny, nz) = chi_nii.dims;
    let (vsx, vsy, vsz) = chi_nii.voxel_size;
    let mask: Vec<u8> = mask_nii.data.iter()
        .map(|&v| if v > 0.5 { 1u8 } else { 0u8 })
        .collect();

    let n = nx * ny * nz;
    let brain_count = mask.iter().filter(|&&m| m > 0).count();
    println!("[INFO] Volume: {}x{}x{} ({} voxels, {} brain)", nx, ny, nz, n, brain_count);
    println!("[INFO] Voxel size: {:.2}x{:.2}x{:.2} mm", vsx, vsy, vsz);

    // Acquisition parameters
    let bdir = (0.0, 0.0, 1.0);
    let b0 = 7.0; // Tesla
    let gamma = 42.576e6; // Hz/T
    let cf = b0 * gamma; // ~298 MHz

    // Compute local field from total chi via dipole convolution
    println!("[INFO] Computing local field via dipole convolution...");
    let start = Instant::now();
    let local_field_hz = compute_local_field_hz(
        &chi_nii.data, &mask, nx, ny, nz, vsx, vsy, vsz, bdir, cf,
    );
    println!("[INFO] Field computation done in {:.2?}", start.elapsed());

    // Print ground truth stats
    let gt_pos_max = chi_pos_gt.data.iter().cloned().fold(0.0f64, f64::max);
    let gt_neg_max = chi_neg_gt.data.iter().cloned().fold(0.0f64, f64::max);
    println!("[INFO] Ground truth chi_pos: max={:.4} ppm", gt_pos_max);
    println!("[INFO] Ground truth |chi_neg|: max={:.4} ppm", gt_neg_max);

    // Parameter sweep
    // Key changes from paper analysis:
    //   1. dr_pos = dr_neg (paper uses equal relaxivities)
    //   2. TV on sum (chi+ + chi-) now included in implementation
    //   3. Sweep lambda_cpl and iterations
    struct ParamSet {
        name: &'static str,
        lambda_para: f64,
        lambda_dia: f64,
        lambda_cpl: f64,
        dr_pos: f64,
        dr_neg: f64,
        max_iter: usize,
        tol: f64,
    }

    let param_sets = vec![
        // Use matching Dr values (114/30) since that's how the phantom R2' was generated
        ParamSet { name: "A: orig_dr, cpl=100, iter=30",
            lambda_para: 1000.0, lambda_dia: 1000.0, lambda_cpl: 100.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
        ParamSet { name: "B: orig_dr, cpl=500, iter=30",
            lambda_para: 1000.0, lambda_dia: 1000.0, lambda_cpl: 500.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
        ParamSet { name: "C: orig_dr, cpl=1000, iter=30",
            lambda_para: 1000.0, lambda_dia: 1000.0, lambda_cpl: 1000.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
        ParamSet { name: "D: tv=100, orig_dr, cpl=100, iter=30",
            lambda_para: 100.0, lambda_dia: 100.0, lambda_cpl: 100.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
        ParamSet { name: "E: tv=100, orig_dr, cpl=500, iter=30",
            lambda_para: 100.0, lambda_dia: 100.0, lambda_cpl: 500.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
        ParamSet { name: "F: tv=10, orig_dr, cpl=100, iter=30",
            lambda_para: 10.0, lambda_dia: 10.0, lambda_cpl: 100.0,
            dr_pos: 114.0, dr_neg: 30.0, max_iter: 30, tol: 0.01 },
    ];

    let dims = chi_nii.dims;
    let vs = chi_nii.voxel_size;
    let affine = &chi_nii.affine;

    println!("\n{:<50} {:>8} {:>8} {:>10} {:>10} {:>8}",
        "Config", "r_pos", "r_neg", "rmse_pos", "rmse_neg", "time_s");
    println!("{}", "-".repeat(100));

    for ps in &param_sets {
        let start = Instant::now();
        let (chi_pos_result, chi_neg_result, _chi_total_result) = chi_sep_medi(
            &local_field_hz,
            &r2prime_nii.data,
            &mag_nii.data,
            &mask,
            nx, ny, nz,
            vsx, vsy, vsz,
            bdir,
            cf,
            ps.lambda_para,
            ps.lambda_dia,
            ps.lambda_cpl,
            ps.dr_pos,
            ps.dr_neg,
            0.3,
            0.01,
            100,
            ps.max_iter,
            ps.tol,
        );
        let elapsed = start.elapsed();

        let corr_pos = correlation(&chi_pos_result, &chi_pos_gt.data, &mask);
        let chi_neg_abs: Vec<f64> = chi_neg_result.iter().map(|&v| v.abs()).collect();
        let corr_neg = correlation(&chi_neg_abs, &chi_neg_gt.data, &mask);
        let rmse_pos = rmse(&chi_pos_result, &chi_pos_gt.data, &mask);
        let rmse_neg = rmse(&chi_neg_abs, &chi_neg_gt.data, &mask);

        println!("{:<50} {:>8.4} {:>8.4} {:>10.4} {:>10.4} {:>8.1}",
            ps.name, corr_pos, corr_neg, rmse_pos, rmse_neg, elapsed.as_secs_f64());

        // Save best config outputs
        if ps.name.starts_with("C") {
            let out_dir = Path::new("chisep_output");
            std::fs::create_dir_all(out_dir).expect("Failed to create output dir");
            qsm_core::nifti_io::save_nifti_to_file(&out_dir.join("chi_pos.nii"), &chi_pos_result, dims, vs, affine).unwrap();
            qsm_core::nifti_io::save_nifti_to_file(&out_dir.join("chi_neg.nii"), &chi_neg_result, dims, vs, affine).unwrap();
            qsm_core::nifti_io::save_nifti_to_file(&out_dir.join("chi_total.nii"), &_chi_total_result, dims, vs, affine).unwrap();
        }
    }

    println!("\nParameter sweep complete!");
}
