//! Integration test: 2D multi-slice QSM on the qsm-forward 2D phantom.
//!
//! Covers the two pieces of 2D multi-slice support against data with known ground truth:
//!
//! * slice-wise phase unwrapping (`qsm_core::unwrap::unwrap_slicewise_multi_echo`) against
//!   the ordinary 3D unwrappers, on a stack whose slices carry independent receive phase
//!   offsets, and which half of it fixes what;
//! * the slice-gap refusal, on an acquisition whose sidecar really is gapped.
//!
//! The phantom is generated by qsm-forward (astewartau/qsm-forward#10) and is not part of
//! this repository. Build it with `qsm_forward/examples/multislice_2d.py`, or point
//! `QSM_BIDS_2D` at an existing copy. Sessions used:
//!
//! | session | geometry | slice phase offsets |
//! |---|---|---|
//! | `thick`   | 1x1x3 mm, contiguous      | none |
//! | `offsets` | 1x1x3 mm, contiguous      | interleaved |
//! | `gap`     | 3 mm slabs at a 4 mm pitch | interleaved |
//!
//! Run with:
//!   QSM_BIDS_2D=~/bids-2d cargo test --release --features parallel --test multislice_2d \
//!     -- --ignored --nocapture

mod common;

use common::{correlation, load_nifti_file};
use qsm_core::pipeline::{run_bg_removal, BgRemovalConfig, ScanMetadata};
use qsm_core::unwrap::{
    unwrap_romeo_multi_echo, unwrap_slicewise_multi_echo, RomeoParams, SliceWiseParams,
    UnwrapMethod,
};
use qsm_core::grid::SliceGeometry;
use qsm_core::Grid;
use std::path::{Path, PathBuf};

const TES: [f64; 4] = [4e-3, 12e-3, 20e-3, 28e-3];
const SLICE_AXIS: usize = 2;

fn root() -> PathBuf {
    PathBuf::from(
        std::env::var("QSM_BIDS_2D")
            .unwrap_or_else(|_| format!("{}/bids-2d", std::env::var("HOME").unwrap_or_default())),
    )
}

struct Session {
    grid: Grid,
    mask: Vec<u8>,
    phase: Vec<Vec<f64>>,
    mag: Vec<Vec<f64>>,
    /// Total field, un-shimmed. Input to background removal.
    fieldmap: Vec<f64>,
    /// The field the signal was actually generated from: qsm-forward applies a second-order
    /// shim *after* writing `fieldmap`, so `fieldmap` is not what the phase encodes.
    fieldmap_signal: Vec<f64>,
    slice_thickness: f64,
}

/// Load one session, or None when the phantom has not been generated.
fn load(session: &str) -> Option<Session> {
    let root = root();
    // `sub-multislice`, which is what examples/multislice_2d.py writes. This has to track
    // the generator: an earlier revision read `sub-1`, matched nothing the committed example
    // produces, and passed locally only because the copy under QSM_BIDS_2D had been made by
    // an ad-hoc script. Every test then skipped, and the CI job reported green.
    let anat = root.join(format!("sub-multislice/ses-{session}/anat"));
    let deriv =
        root.join(format!("derivatives/qsm-forward/sub-multislice/ses-{session}/anat"));
    // Probe every file this loader needs, not just one image. A phantom generated without
    // `save_shimmed_field=True` has all the images and is missing only `desc-shimmed_fieldmap`,
    // so probing the phase alone would send a stale phantom into an unwrap panic on a derivative
    // several lines later, with nothing saying which flag was missing.
    let required = [
        anat.join(format!("sub-multislice_ses-{session}_echo-1_part-phase_MEGRE.nii")),
        anat.join(format!("sub-multislice_ses-{session}_echo-4_part-mag_MEGRE.nii")),
        anat.join(format!("sub-multislice_ses-{session}_echo-1_part-phase_MEGRE.json")),
        deriv.join(format!("sub-multislice_ses-{session}_mask.nii")),
        deriv.join(format!("sub-multislice_ses-{session}_fieldmap.nii")),
        // only written when generate_bids is given save_shimmed_field=True, and the only
        // correct comparison target for anything that goes through the signal
        deriv.join(format!("sub-multislice_ses-{session}_desc-shimmed_fieldmap.nii")),
    ];
    if let Some(missing) = required.iter().find(|p| !Path::new(p).exists()) {
        println!("Skipping: 2D phantom session '{session}' is missing {}", missing.display());
        println!(
            "  regenerate with qsm_forward/examples/multislice_2d.py (which passes \
             save_shimmed_field=True), or point QSM_BIDS_2D at a copy that has it"
        );
        return None;
    }

    let f = |p: PathBuf| load_nifti_file(p.to_str().unwrap()).unwrap();
    let phase: Vec<Vec<f64>> = (1..=4)
        .map(|e| f(anat.join(format!("sub-multislice_ses-{session}_echo-{e}_part-phase_MEGRE.nii"))).data)
        .collect();
    let mag: Vec<Vec<f64>> = (1..=4)
        .map(|e| f(anat.join(format!("sub-multislice_ses-{session}_echo-{e}_part-mag_MEGRE.nii"))).data)
        .collect();
    let mask_nii = f(deriv.join(format!("sub-multislice_ses-{session}_mask.nii")));
    let (nx, ny, nz) = mask_nii.dims;
    let (vx, vy, vz) = mask_nii.voxel_size;

    // SliceThickness from the sidecar: the NIfTI spacing is the slice pitch, which for a
    // gapped acquisition is larger. This is the whole input to the contiguity check.
    let sidecar = std::fs::read_to_string(
        anat.join(format!("sub-multislice_ses-{session}_echo-1_part-phase_MEGRE.json")),
    )
    .unwrap();
    let json: serde_json::Value = serde_json::from_str(&sidecar).unwrap();
    let slice_thickness = json["SliceThickness"].as_f64().unwrap_or(vz);

    Some(Session {
        grid: Grid::new(nx, ny, nz, vx, vy, vz),
        mask: mask_nii.data.iter().map(|&m| u8::from(m > 0.5)).collect(),
        phase,
        mag,
        fieldmap: f(deriv.join(format!("sub-multislice_ses-{session}_fieldmap.nii"))).data,
        fieldmap_signal: f(deriv.join(format!("sub-multislice_ses-{session}_desc-shimmed_fieldmap.nii"))).data,
        slice_thickness,
    })
}

/// Per-voxel least-squares slope of unwrapped phase against TE: the `linear-fit` B0 estimate.
/// Returned in rad/s, which is the ground-truth field up to one scale factor - so these are
/// only ever compared by correlation, never by value.
fn fit_slope(unwrapped: &[Vec<f64>], tes: &[f64]) -> Vec<f64> {
    let n = tes.len() as f64;
    let te_mean = tes.iter().sum::<f64>() / n;
    let sxx: f64 = tes.iter().map(|t| (t - te_mean).powi(2)).sum();
    (0..unwrapped[0].len())
        .map(|i| {
            let y_mean = unwrapped.iter().map(|u| u[i]).sum::<f64>() / n;
            tes.iter()
                .zip(unwrapped)
                .map(|(t, u)| (t - te_mean) * (u[i] - y_mean))
                .sum::<f64>()
                / sxx
        })
        .collect()
}

/// Best correlation either 3D ROMEO path reaches **unaided** — that is, without
/// `enforce_inter_echo_consistency`. The `_unaided` is the whole point: 3D ROMEO *with* the pass
/// reaches 0.983 too, which `the_consistency_pass_fixes_the_fit_and_slice_wise_fixes_the_phase`
/// pins. Comparing slice-wise-with-the-pass against 3D-with-the-pass on this metric would show
/// no difference, because a fitted slope cannot see what slice-wise does.
fn best_3d_unaided(s: &Session) -> (f64, &'static str) {
    [("template", false), ("individual", true)]
        .map(|(name, individual)| {
            let params = RomeoParams { individual, ..RomeoParams::default() };
            let u = unwrap_romeo_multi_echo(&s.phase, &s.mag, &TES, &s.mask, &params, &s.grid);
            (correlation(&fit_slope(&u, &TES), &s.fieldmap_signal, &s.mask), name)
        })
        .into_iter()
        .max_by(|a, b| a.0.partial_cmp(&b.0).unwrap())
        .unwrap()
}

fn slicewise_corr(s: &Session) -> f64 {
    let u = unwrap_slicewise_multi_echo(
        &s.phase, &s.mag, &TES, &s.mask, UnwrapMethod::Romeo,
        &SliceWiseParams { slice_axis: SLICE_AXIS, ..SliceWiseParams::default() },
        &s.grid,
    );
    correlation(&fit_slope(&u, &TES), &s.fieldmap_signal, &s.mask)
}

#[test]
#[ignore] // needs the qsm-forward 2D phantom; run with --release --ignored
fn slicewise_beats_unaided_3d_on_slices_with_phase_offsets() {
    // Named for what it compares. The 3D baseline here has no consistency pass, and that is the
    // only reason slice-wise wins on this metric - give 3D the pass and it reaches 0.983 too.
    // What slice-wise is actually for is the spatial continuity of the phase, which a fitted
    // slope cannot see; that is
    // `the_consistency_pass_fixes_the_fit_and_slice_wise_fixes_the_phase`.
    let Some(s) = load("offsets") else { return };
    println!("offsets session: {:?} at {:?} mm", s.grid.dims, s.grid.voxel_size);

    let (r_3d, which) = best_3d_unaided(&s);
    let r_2d = slicewise_corr(&s);
    println!("RESULT:unwrap_3d_unaided_corr={r_3d:.4} ({which})");
    println!("RESULT:unwrap_slicewise_romeo_corr={r_2d:.4}");

    assert!(r_2d > 0.95, "slice-wise B0 fit correlation only {r_2d:.4}");
    assert!(
        r_2d > r_3d + 0.02,
        "slice-wise ({r_2d:.4}) is not better than the best unaided 3D path ({r_3d:.4}, \
         {which}) on data whose slices carry independent phase offsets"
    );
}

/// Bounds the recommendation. The module docs and the README both say to prefer ROMEO or best
/// path over the Laplacian for slice-wise unwrapping, and quote 0.81 against 0.983 for it. That
/// figure had nothing asserting it, so a regression would have left a stale recommendation
/// rather than a failing test — the Laplacian could have gone to 0.3 and the docs would still
/// have said 0.81.
///
/// The ordering is the claim; the figures are colour. The Laplacian trails because its Poisson
/// solution is not a whole number of wraps from the truth to begin with, so the per-voxel
/// consistency pass cannot fully re-seat it — but it should still be usable, not broken, which
/// is what the lower bound is for.
#[test]
#[ignore]
fn slicewise_laplacian_trails_the_region_growers_but_is_not_broken() {
    let Some(s) = load("offsets") else { return };
    let corr = |method| {
        let params = SliceWiseParams { slice_axis: SLICE_AXIS, ..SliceWiseParams::default() };
        let u = unwrap_slicewise_multi_echo(
            &s.phase, &s.mag, &TES, &s.mask, method, &params, &s.grid,
        );
        correlation(&fit_slope(&u, &TES), &s.fieldmap_signal, &s.mask)
    };
    let romeo = corr(UnwrapMethod::Romeo);
    let bestpath = corr(UnwrapMethod::BestPath);
    let laplacian = corr(UnwrapMethod::Laplacian);
    println!("RESULT:unwrap_slicewise_romeo_offsets_corr={romeo:.4}");
    println!("RESULT:unwrap_slicewise_bestpath_offsets_corr={bestpath:.4}");
    println!("RESULT:unwrap_slicewise_laplacian_offsets_corr={laplacian:.4}");

    assert!(romeo > 0.95, "slice-wise ROMEO: {romeo:.4}");
    assert!(bestpath > 0.95, "slice-wise best path: {bestpath:.4}");
    assert!(
        laplacian < romeo - 0.1,
        "slice-wise Laplacian ({laplacian:.4}) no longer trails ROMEO ({romeo:.4}) — if that is \
         real, the \"prefer ROMEO or best path\" guidance in the module docs and README is stale"
    );
    // This bound was set by measuring 0.8140 and backing off, and no mutation has been found
    // that trips it: removing the Laplacian's re-anchoring leaves it passing (the consistency
    // pass re-seats the echoes afterwards), and making the Laplacian return the wrapped input
    // trips the *upper* bound instead, at 0.9830. So treat it as an unearned floor that would
    // catch a gross regression, not as a pinned property - the trails-ROMEO bound above is the
    // one with a demonstrated null.
    assert!(
        laplacian > 0.55,
        "slice-wise Laplacian has gone from trailing to broken ({laplacian:.4}); the docs quote \
         0.81 and describe it as usable-but-worse"
    );
}

#[test]
#[ignore]
fn slicewise_does_not_lose_ground_when_there_are_no_slice_offsets() {
    // The control: with no per-slice offsets, the slice-wise mode must not be making things
    // worse. That is the load-bearing claim and it is the second assertion.
    //
    // An earlier revision also asserted `r_3d > 0.95`, on the assumption that 3D unwrapping is
    // healthy whenever the offsets are absent. That is false on this phantom and the assumption
    // was the thing worth losing: 3 mm slices alone produce through-slice phase steps large
    // enough to mislead a region grower, with no receive offset involved. 3D reaches 0.9363
    // here against slice-wise's 0.9833, so the mode is not merely harmless without offsets, it
    // is still ahead. The lower bound below only guards against 3D collapsing far enough that
    // the comparison stops meaning anything.
    let Some(s) = load("thick") else { return };
    let (r_3d, which) = best_3d_unaided(&s);
    let r_2d = slicewise_corr(&s);
    println!("RESULT:unwrap_3d_nooffsets_corr={r_3d:.4} ({which})");
    println!("RESULT:unwrap_slicewise_nooffsets_corr={r_2d:.4}");
    assert!(
        r_3d > 0.8,
        "3D has collapsed without offsets ({r_3d:.4}), so this is no longer a control"
    );
    assert!(
        r_2d > r_3d,
        "slice-wise ({r_2d:.4}) lost ground against 3D ({r_3d:.4}, {which}) on data with no \
         offsets"
    );
}

/// The slice-gap refusal, on a real gapped acquisition rather than a synthetic one.
///
/// The unit tests in `pipeline` construct a `ScanMetadata` by hand and prove the wiring; this
/// one reads a thickness out of a sidecar the phantom actually wrote and puts it through the
/// stage a user hits. That is the part no unit test can cover: that a real BIDS sidecar and a
/// real NIfTI spacing combine into a refusal rather than into a plausible-looking field map.
#[test]
#[ignore]
fn a_gapped_acquisition_is_refused_by_the_pipeline() {
    let Some(s) = load("gap") else { return };
    // the sidecar must actually describe a gap, or this test is checking nothing
    let pitch = s.grid.vsz();
    assert!(
        s.slice_thickness < pitch - 0.1,
        "the 'gap' session is not gapped: {} mm slices at a {} mm pitch",
        s.slice_thickness, pitch
    );

    let mut meta = ScanMetadata {
        dims: s.grid.dims,
        voxel_size: s.grid.voxel_size,
        echo_times: TES.to_vec(),
        field_strength: 3.0,
        b0_direction: (0.0, 0.0, 1.0),
        slice_geometry: Some(SliceGeometry { thickness: s.slice_thickness, axis: SLICE_AXIS }),
    };
    let cfg = BgRemovalConfig::default();
    let Err(err) = run_bg_removal(&s.fieldmap, &s.mask, &meta, &cfg, &mut |_, _| {}) else {
        panic!("a gapped acquisition must be refused, not computed");
    };
    println!("RESULT:bfr_gap_refused={err}");

    // and the same data, declared contiguous, is accepted - so the refusal is reading the
    // thickness and not just failing on this session for some other reason
    meta.slice_geometry = Some(SliceGeometry { thickness: pitch, axis: SLICE_AXIS });
    assert!(run_bg_removal(&s.fieldmap, &s.mask, &meta, &cfg, &mut |_, _| {}).is_ok());
    // and the message names the geometry, so the person who scanned it can act on it
    let msg = err.to_string();
    for part in ["3.0000", "4.0000", "1.0000", "not contiguous"] {
        assert!(msg.contains(part), "the refusal does not mention {part}: {msg}");
    }
}

/// Which half does which job, on real data. The fit-correlation metric used by the two tests
/// above cannot tell slice-wise unwrapping from the consistency pass, because a fitted slope is
/// blind to a constant per voxel — both reach 0.983. This is the measure on which they come
/// apart, and it is the one that justifies the slice-wise mode for anything reading the phase.
#[test]
#[ignore]
fn the_consistency_pass_fixes_the_fit_and_slice_wise_fixes_the_phase() {
    let Some(s) = load("offsets") else { return };
    let (nx, ny, nz) = s.grid.dims;
    let refs: Vec<&[f64]> = s.phase.iter().map(|p| p.as_slice()).collect();
    let corr = |u: &[Vec<f64>]| correlation(&fit_slope(u, &TES), &s.fieldmap_signal, &s.mask);
    let jumps = |v: &[f64]| {
        let mut n = 0usize;
        for k in 0..nz {
            for j in 0..ny {
                for i in 0..nx - 1 {
                    let a = i + j * nx + k * nx * ny;
                    if s.mask[a] != 0 && s.mask[a + 1] != 0
                        && (v[a + 1] - v[a]).abs() > std::f64::consts::PI
                    {
                        n += 1;
                    }
                }
            }
        }
        n
    };

    // the pass alone, applied to phase nothing has spatially unwrapped
    let mut raw = s.phase.clone();
    let raw_before = corr(&raw);
    qsm_core::unwrap::enforce_inter_echo_consistency(&mut raw, &refs, &s.mask);
    let raw_after = corr(&raw);

    // the pass applied to 3D ROMEO's output, which fails unaided
    let params = RomeoParams { individual: true, ..RomeoParams::default() };
    let mut three_d =
        unwrap_romeo_multi_echo(&s.phase, &s.mag, &TES, &s.mask, &params, &s.grid);
    let three_d_before = corr(&three_d);
    qsm_core::unwrap::enforce_inter_echo_consistency(&mut three_d, &refs, &s.mask);
    let three_d_after = corr(&three_d);

    let sw_params = SliceWiseParams { slice_axis: SLICE_AXIS, ..SliceWiseParams::default() };
    let slicewise = unwrap_slicewise_multi_echo(
        &s.phase, &s.mag, &TES, &s.mask, UnwrapMethod::Romeo, &sw_params, &s.grid,
    );

    let last = TES.len() - 1;
    println!("RESULT:fit_raw_before={raw_before:.4} fit_raw_after={raw_after:.4}");
    println!("RESULT:fit_3d_before={three_d_before:.4} fit_3d_after={three_d_after:.4}");
    println!("RESULT:fit_slicewise={:.4}", corr(&slicewise));
    println!(
        "RESULT:jumps_wrapped={} jumps_pass_only={} jumps_slicewise={}",
        jumps(&s.phase[last]), jumps(&raw[last]), jumps(&slicewise[last])
    );

    // the pass is what fixes the fit, from either starting point
    assert!(raw_before < 0.5, "raw wrapped fit should be poor: {raw_before:.4}");
    assert!(raw_after > 0.95, "the pass alone did not fix the fit: {raw_after:.4}");
    assert!(three_d_before < 0.5, "3D should fail unaided: {three_d_before:.4}");
    assert!(three_d_after > 0.95, "the pass did not fix 3D: {three_d_after:.4}");

    // And slice-wise is what fixes the phase, which the fit cannot see. Echo 0 is the clean
    // measurement and clean *by construction*: the pass loops `for e in 1..n_echoes` and writes
    // only `unwrapped[e]`, so it cannot touch the first echo. No null is needed to rule the pass
    // out here - the structure does it, and the equality below is what checks the structure
    // still holds.
    println!(
        "RESULT:jumps_echo0_wrapped={} jumps_echo0_pass_only={} jumps_echo0_slicewise={}",
        jumps(&s.phase[0]), jumps(&raw[0]), jumps(&slicewise[0])
    );
    assert_eq!(
        jumps(&raw[0]), jumps(&s.phase[0]),
        "the pass changed echo 0, which it cannot do if it only writes echoes 1.. - the \
         structural argument this test rests on is broken"
    );
    assert!(
        jumps(&slicewise[0]) * 4 < jumps(&raw[0]),
        "slice-wise left {} in-plane jumps in echo 0 against the pass's untouched {}; that \
         difference is attributable to the spatial unwrapping alone",
        jumps(&slicewise[0]), jumps(&raw[0])
    );

    // The last echo has both mechanisms in play, so this comparison does need the null.
    let (pass_only, with_slicewise) = (jumps(&raw[last]), jumps(&slicewise[last]));
    assert!(
        with_slicewise < pass_only / 2,
        "slice-wise left {with_slicewise} in-plane 2pi jumps against the pass alone's \
         {pass_only}; if that gap has closed, the module docs and README overstate what the \
         slice-wise mode is for"
    );
}
